// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import SearchableSelectController from "./searchable_select_controller.js"
application.register("searchable-select", SearchableSelectController)

import SortableTableController from "./sortable_table_controller.js"
application.register("sortable-table", SortableTableController)
